on:
  pull_request:
    paths:
      - "docs/**/*.md"
  push:
    branches:
      - main
    paths:
      - "docs/**/*.md"
permissions:
  contents: read

name: huggingface-dataset


jobs:
  publish-dataset:
    name: Publish dataset to huggingface hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
    
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.7.10"
          enable-cache: true
          cache-dependency-glob: "./projects/pgai/uv.lock"

      - name: Check dataset
        if: github.event_name == 'pull_request'
        run: ./scripts/generate_huggingface_dataset.py check

      - name: Push dataset
        if: github.event_name == 'push'
        env:
          HUGGINGFACE_HUB_TIMESCALE_TOKEN: ${{ secrets.HUGGINGFACE_HUB_TIMESCALE_TOKEN }}
        run: ./scripts/generate_huggingface_dataset.py push
